version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: agent_chat_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agent_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: agent_chat_redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

volumes:
  postgres_data: 